In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("Iris.csv")

In [4]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [6]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [7]:
grouped = df.groupby("Species").agg(["mean", "median", "std", "min", "max"])

In [8]:
print(grouped)

                    Id                            SepalLengthCm         \
                  mean median       std  min  max          mean median
Species
Iris-setosa       25.5   25.5  14.57738    1   50         5.006    5.0
Iris-versicolor   75.5   75.5  14.57738   51  100         5.936    5.9
Iris-virginica   125.5  125.5  14.57738  101  150         6.588    6.5

                                     ... PetalLengthCm                        \
                      std  min  max  ...          mean median       std  min
Species                              ...
Iris-setosa      0.352490  4.3  5.8  ...         1.464   1.50  0.173511  1.0
Iris-versicolor  0.516171  4.9  7.0  ...         4.260   4.35  0.469911  3.0
Iris-virginica   0.635880  4.9  7.9  ...         5.552   5.55  0.551895  4.5

                     PetalWidthCm
                 max         mean median       std  min  max
Species
Iris-setosa      1.9        0.244    0.2  0.107210  0.1  0.6
Iris-versicolor  5.1        1.326    1.3  0.197753  1.0  1.8
Iris-virginica   6.9        2.026    2.0  0.274650  1.4  2.5

[3 rows x 25 columns]